# Python Django
# Test a Django app on multiple versions of Python.
# https://aka.ms/yaml

## NOTE! You need to set the projectRoot in both phases (until VSTS supports YAML anchors).

phases:

# =================
# Test a Django app
# =================
- phase: 'DjangoApp'
  variables:
    projectRoot: mysite/  # relative path to the directory containing manage.py

  queue:
    name: 'Hosted Linux Preview'
    parallel: 1
    matrix:
      Python35:
        PYTHON_VERSION: '3.5'
      Python36:
        PYTHON_VERSION: '3.6'
      Python37-dev:
        PYTHON_VERSION: '>= 3.7.0a'
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install dependencies'

  - script: python -m pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: python -m pip install unittest-xml-reporting
    displayName: 'Install unittest-xml-reporting'

  - script: pushd $(projectRoot) && python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
    displayName: 'Run tests'
  
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/TEST-*.xml"
      searchFolder: $(system.defaultWorkingDirectory)/$(projectRoot)
      testRunTitle: 'Python $(PYTHON_VERSION)'


# ===============================================
# Phase 2: Copy sources to prepare for publishing
# ===============================================
- phase: 'PublishProjectArtifact'
  dependsOn: 'DjangoApp'
  variables:
    projectRoot: mysite/  # relative path to the directory containing manage.py
  queue: 'Hosted Linux Preview'

  steps:

  - task: CopyFiles@2
    displayName: 'Stage project directory'
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/$(projectRoot)'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(build.artifactStagingDirectory)
      artifactName: 'django-project'
      publishLocation: 'container'
